"""create person, face_embedding and recognition_log

Revision ID: a3d14595db3b
Revises: 
Create Date: 2026-09-13 08:55:01.256301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d14595db3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_name'), ['name'], unique=True)

    op.create_table('face_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_embedding_person_id'), ['person_id'], unique=False)

    op.create_table('recognition_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recognition_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recognition_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recognition_log_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognition_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recognition_log_person_id'))
        batch_op.drop_index(batch_op.f('ix_recognition_log_created_at'))

    op.drop_table('recognition_log')
    with op.batch_alter_table('face_embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_embedding_person_id'))

    op.drop_table('face_embedding')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_name'))

    op.drop_table('person')
    # ### end Alembic commands ###
